# SonarQube configuration
sonar.projectKey=Chat
sonar.projectName=Chat
sonar.projectVersion=0.2.1

# Source directories
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**
sonar.exclusions=deps/**,_build/**,assets/**,rel/**,priv/**,node_modules/**,.elixir_ls/**,cover/**,.scannerwork/**,test/**

# Source encoding
sonar.sourceEncoding=UTF-8

# Elixir source files
sonar.lang.patterns.elixir=**/*.ex,**/*.exs

# Coverage report (excoveralls XML)
sonar.coverage.jacocoXmlReportPaths=cover/jacoco.xml

# Host configuration
sonar.host.url=http://localhost:9001
sonar.token=sqp_dee05c6d3e216c40cac17dcd2392e4dd614b4d57
